version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bl_agent_server
    image: bl_agent/server:01
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma:/app/chroma:rw
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ../mongo:/data/db:rw
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"

  # chroma:
  #   image: chromadb/chroma
  #   container_name: bl_agent_chat_chroma
  #   ports:
  #     - "8001:8000"
  #   restart: unless-stopped
  #   volumes:
  #     - ./chroma:/chroma/chroma:rw
