"""modify the website table

Revision ID: 45865e9f484a
Revises: 7b69060ff190
Create Date: 2024-09-04 07:34:23.423033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45865e9f484a'
down_revision = '7b69060ff190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'websites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'websites', type_='foreignkey')
    op.drop_column('websites', 'user_id')
    # ### end Alembic commands ###
