"""user table create_by_id and update_by_id field added

Revision ID: 5050559c0c84
Revises: 843cc0761546
Create Date: 2024-09-03 05:33:46.889470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5050559c0c84'
down_revision = '843cc0761546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['deleted_by_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_by_id')
    op.drop_column('users', 'updated_by_id')
    op.drop_column('users', 'created_by_id')
    # ### end Alembic commands ###
