"""added unique

Revision ID: 61c2791d3f5b
Revises: 45865e9f484a
Create Date: 2024-09-04 13:18:26.800787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c2791d3f5b'
down_revision = '45865e9f484a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'websites', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'websites', type_='unique')
    # ### end Alembic commands ###
