"""foreign key was added to the specified field.

Revision ID: 843cc0761546
Revises: dbad70fc370f
Create Date: 2024-09-02 08:33:46.412573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843cc0761546'
down_revision = 'dbad70fc370f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('menus', sa.Column('module_id', sa.Integer(), nullable=True))
    op.add_column('menus', sa.Column('parent_menu', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menus', 'menus', ['parent_menu'], ['id'])
    op.create_foreign_key(None, 'menus', 'modules', ['module_id'], ['id'])
    op.add_column('permissions', sa.Column('group_id', sa.Integer(), nullable=False))
    op.add_column('permissions', sa.Column('menu_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'permissions', 'menus', ['menu_id'], ['id'])
    op.create_foreign_key(None, 'permissions', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'menu_id')
    op.drop_column('permissions', 'group_id')
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_column('menus', 'parent_menu')
    op.drop_column('menus', 'module_id')
    op.drop_table('user_type')
    # ### end Alembic commands ###
