"""modification website settings

Revision ID: eb3427015879
Revises: 5a2b60dc741b
Create Date: 2024-09-03 05:58:15.435926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3427015879'
down_revision = '5a2b60dc741b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_settings', sa.Column('website_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'website_settings', 'websites', ['website_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'website_settings', type_='foreignkey')
    op.drop_column('website_settings', 'website_id')
    # ### end Alembic commands ###
