"""added new column

Revision ID: fa6a33a07129
Revises: cc8bf9b1c875
Create Date: 2024-09-02 13:09:49.887229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6a33a07129'
down_revision = 'cc8bf9b1c875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
